Numpy
Tốc độ của Numpy nhanh hơn python list 50 lầnn

In [6]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 1.03 s
Wall time: 1.07 s


In [5]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 34.4 ms


- Numpy cho phép thực hiện phép toán trên mảng tương tự số thực

In [7]:
import numpy as np
data = np.random.randn(2, 3)
print(data )

print(data * 2)

print(data + data)


[[-0.13130395 -0.89834162 -0.70692553]
 [-1.67144387  0.32314845  1.76864874]]
[[-0.26260789 -1.79668323 -1.41385106]
 [-3.34288774  0.6462969   3.53729747]]
[[-0.26260789 -1.79668323 -1.41385106]
 [-3.34288774  0.6462969   3.53729747]]


Cách khởi tạo mảng trong NumPy
- Đưa mảảng python sang numpy

In [11]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
import numpy as np

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Khởi tạo mảng với các phần tử 0


In [23]:
import numpy as np
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
import numpy as np
np.empty((2, 3, 4))

array([[[1.30343498e-311, 1.30339169e-311, 1.69121096e-306,
         1.78021119e-306],
        [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
         1.11261095e-306],
        [3.56043054e-307, 1.37961641e-306, 2.22518251e-306,
         1.33511969e-306]],

       [[6.23037996e-307, 9.34609790e-307, 8.45593934e-307,
         9.34600963e-307],
        [3.56036603e-307, 1.37961641e-306, 1.37961302e-306,
         1.11259940e-306],
        [1.60219035e-306, 1.11261570e-306, 1.06811354e-306,
         8.34448533e-308]]])

Khi khai baos zeros trc thì empty khai báo sau sẽ ăn cùng bộ nhớ với zeroszeros

Cách khai báo mảng khác:

In [6]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [16]:
import numpy as np
numeric_strings = np.array(['1.25','-9.6', '42'], dtype=np.bytes_) #version mới dùng bytes_
print(numeric_strings)
numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

Vecto hóa toán tử( thực hiện tuần tự trên từng phần tử)

In [17]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr*arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)
print(arr*arr)
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr>arr2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[ True False  True]
 [False  True False]]


Để thao tác với các phần tử hay các tập
con trong mảng của NumPy, ta thao tác
như List của Python

In [18]:
import numpy as np
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:-1])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]


In [20]:
import numpy as np
data = np.random.randn(2, 2, 3)
data[:]

array([[[-1.41990905, -0.18129978, -0.88287636],
        [-0.82606018,  0.71986134, -0.49893082]],

       [[ 0.54191228,  1.01160886,  1.07689823],
        [-2.0724031 ,  0.7669747 ,  0.44771559]]])

In [24]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
print(names=='Bob')
print(data[names=='Bob']) # Vị trí name = Bob
print(data[names=='Bob', 2:3])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.78117688  0.91475089 -0.26793824  1.22795861]
 [-0.20237542 -0.05824417 -0.31032204  0.5319095 ]
 [-0.2732606   0.49408975 -0.36354    -0.96096622]
 [-1.5321392  -0.16867647 -2.62963099  0.27525562]
 [ 0.904384   -0.23021974  0.21840057  1.53483645]
 [-1.39793208  0.23623755  0.58310067  1.58173964]
 [-0.63473421 -1.84222045 -1.36216294  1.66260611]]
[ True False False  True False False False]
[[-0.78117688  0.91475089 -0.26793824  1.22795861]
 [-1.5321392  -0.16867647 -2.62963099  0.27525562]]
[[-0.26793824]
 [-2.62963099]]


In [26]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
