Bài tập 1: 
a) HOàn thành hàm tính độ dài vecto

In [2]:
import numpy as np

def compute_vecto_len(vector):
    len_of_vecto =  np.sqrt(np.sum(np.square(vector)))
    return len_of_vecto

vecto = np.array([3, 6])
print(compute_vecto_len(vecto))

6.708203932499369


b) Phép tính tích vô hướng - Dot product

In [5]:
import numpy as np

def dot_product(a, b):
    result = np.sum(a * b)
    return result

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(dot_product(a, b))

32


c) Nhân vecto với ma trận

In [10]:
import numpy as np

def matrix_multi_vecto(matrix, vector):
    result = np.dot(matrix, vector)
    return result

matrix = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
vector = np.array([2, 
                   4,
                   6])

print(matrix_multi_vecto(matrix, vector))

[28 64 88]


d) Nhân ma trận với ma trận

In [11]:
import numpy as np

def matrix_multi_matrix(a, b):
    result = np.dot(a, b)
    return result

a = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
b = np.array([[2, 4, 6], [1, 3, 5], [7, 8, 9]])
print(matrix_multi_matrix(a, b))

[[ 25  34  43]
 [ 59  80 101]
 [ 79 110 141]]


e) Ma trận nghịch đảo
Bt:
Cho trước A = [ -2 6 ][8 -4]
Determinant A = -2*-2 -6*8 = -40
inverser A^-1 = 1/-40 * [-4 -6][-8 -2] = [1/10  3/20][1/5  1/20] 

In [12]:
def inverse_matrix(a):
    result = np.linalg.inv(a)
    return result

a = np.array([[-2, 6], [8, -4]])
print(inverse_matrix(a))

[[0.1  0.15]
 [0.2  0.05]]
