Bài tập 1: 
a) HOàn thành hàm tính độ dài vecto

In [2]:
import numpy as np

def compute_vecto_len(vector):
    len_of_vecto =  np.sqrt(np.sum(np.square(vector)))
    return len_of_vecto

vecto = np.array([3, 6])
print(compute_vecto_len(vecto))

6.708203932499369


b) Phép tính tích vô hướng - Dot product

In [1]:
import numpy as np

def dot_product(a, b):
    result = np.sum(a * b)
    return result

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(dot_product(a, b))

32


c) Nhân vecto với ma trận

In [10]:
import numpy as np

def matrix_multi_vecto(matrix, vector):
    result = np.dot(matrix, vector)
    return result

matrix = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
vector = np.array([2, 
                   4,
                   6])

print(matrix_multi_vecto(matrix, vector))

[28 64 88]


d) Nhân ma trận với ma trận

In [3]:
import numpy as np

def matrix_multi_matrix(a, b):
    result = np.dot(a, b)
    return result

a = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
b = np.array([[2, 4, 6], [1, 3, 5], [7, 8, 9]])
print(matrix_multi_matrix(a, b))

[[ 25  34  43]
 [ 59  80 101]
 [ 79 110 141]]


e) Ma trận nghịch đảo
Bt:
Cho trước A = [ -2 6 ][8 -4]
Determinant A = -2*-2 -6*8 = -40
inverser A^-1 = 1/-40 * [-4 -6][-8 -2] = [1/10  3/20][1/5  1/20] 

In [12]:
def inverse_matrix(a):
    result = np.linalg.inv(a)
    return result

a = np.array([[-2, 6], [8, -4]])
print(inverse_matrix(a))

[[0.1  0.15]
 [0.2  0.05]]


Bài tập 2: Eigenvector và eigenvalues

2.1) Eigenvector và eigenvalues
Cho A = [0.9    0.2
        0.1     0.8]

det(A - lamda*I) = 0 
        [0.9 - lamda    0.2
        0.1             0.8 - lamda ] = 0
        --> Eigenvalues: Lamda = 1
                        hoặc Lamda = 0.7

Với lamda = 1 ta có phương trình (A-I).v = 0
--> v1 = 2*v2
--> v = [2 1]
Chuẩn hóa:
|v| = sqrt(4 + 11) = sqrt(5)
Vn = [2/sqrt(5) 1/sqrt(5)]

Với lamda = 0.7 ta có phương trình (A - 0.7I).v =0
--> 0.2v1 + 0.2v2 = 0
--> v1 = -v2
--> v = [-1     1]
Chuẩn hóa:
|v| = sqrt(2)
Vn = [-1/sqrt(2)         1/sqrt(2)]

In [8]:
def compute_eigenvalues_eigenvector (a):

    # Tính eigenvalues và eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(a)

    # Chuẩn hóa eigenvectors
    normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

    # In kết quả
    print("Eigenvalues :", eigenvalues)
    print("Eigenvectors :")
    print(normalized_eigenvectors)
    return eigenvalues, normalized_eigenvectors

A = np.array([[0.9, 0.2], [0.1, 0.8]])
compute_eigenvalues_eigenvector(A)

Eigenvalues : [1.  0.7]
Eigenvectors :
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


(array([1. , 0.7]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

3. Cosine Similarity
Cho trước
x = [ 1   2   3   4]
y = [ 1   0   3   0]
cos(x,y) = (1 + 0 + 9 + 0)/ sqrt(1 + 4 + 9 + 16)*sqrt(1 + 0 + 9 + 0) = 0.57735

In [9]:
def compute_consine(x, y):
    result = np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
    return result

x = np.array([1, 2, 3, 4])
y = np.array([1, 0 ,3, 0])
compute_consine(x, y)

np.float64(0.5773502691896257)